### ISSUE TITLE
Browser auth required, but empty credentials gets through

### ISSUE THREAD

**Issue by fugue88** [atomicjolt/ep_signatureauth#7]
On our dev environment, when I launch a new collaboration from a course, my browser opens a new window pointed at Etherpad.  The server sends back an authentication request (Basic Auth), so the browser pops open a dialog asking for credentials.

If I click Cancel, it simply repeats.

If I click Okay (with empty credentials), I can actually get into the pad and start editing, although the browser keeps opening the credentials dialog.

**Comment by fugue88** [comment]
The `authorize` function doesn't handle the `locales.json` or `jserror` paths correctly.  There may be others.

**Comment by emdurr** [comment]
Most recent pull request is set to fix the locales.json  & jserror functionality as well as the issue with being able to access a pad without Authorization.
https://github.com/atomicjolt/ep_signatureauth/pull/8

Fixed with release 1.1.2
